name: elk

services:
  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - ELASTIC_PASSWORD=password
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic-network

  kibana:
    image: kibana:8.16.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      # host.docker.internal
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=kibana_system
      # - ELASTICSEARCH_PASSWORD=password
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge

