FROM node:20-alpine

WORKDIR /app

# Debug: List environment files
RUN ls -la /.env* || true
RUN ls -la .env* || true

# Install development dependencies only once
COPY package*.json ./
COPY nx.json tsconfig.base.json ./
COPY eslint.config.js jest.preset.js ./

# Install all dependencies (including dev dependencies)
RUN npm ci --legacy-peer-deps
#  && \
#    npm install -g nodemon

# Copy service-specific nodemon configuration
# COPY apps/api-gw/nodemon.json ./nodemon.json

# The source code will be mounted as a volume
# No need to copy source files

# Expose port for development
ENV PORT=${API_GATEWAY_PORT}
EXPOSE ${PORT}
EXPOSE 9229

# Start the application in development mode
# CMD ["npx", "nx", "serve", "api-gw", "--host", "0.0.0.0"]
# CMD ["npx", "nx", "serve", "api-gw", "--watch", "--host", "0.0.0.0"]
# CMD ["nodemon"]
CMD ["npx", "nx", "serve", "api-gw", "--configuration=development"]