### Register assessment
POST http://localhost:3004/api/assessments
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "firstName": "John",
    "lastName": "Doe"
}

### Update assessment profile
@id = ba155cef-f851-4604-ad92-48b1b715beae
PATCH http://localhost:3004/api/assessments/{{id}}/profile
Content-Type: application/json

{
  "gender": "male",
  "country": "Brazil"
  //"state": "São Paulo",
  //"zipCode": "01001-000"
}

### Get Assessment
@id_test = 9412ca1b-e2b3-45ca-a230-8e9dfbccf8af
GET http://localhost:3004/api/assessments/{{id_test}}

### Evaluate results
PATCH http://localhost:3004/api/evaluations/{{id_test}}/evaluate

