export const ENV_KEYS = {
    NODE_ENV: 'NODE_ENV',

    DATABASE_URL: 'DATABASE_URL',
    DATABASE_SCHEMA: 'DATABASE_SCHEMA',
    TEST_DATABASE_SCHEMA: 'TEST_DATABASE_SCHEMA',
    DATABASE_POOL_MIN: 'DATABASE_POOL_MIN',
    DATABASE_POOL_MAX: 'DATABASE_POOL_MAX',
    
    CONSUL_HOST: 'CONSUL_HOST',
    CONSUL_PORT: 'CONSUL_PORT',
    
    API_GATEWAY_ID: 'API_GATEWAY_ID',
    API_GATEWAY_NAME: 'API_GATEWAY_NAME',
    API_GATEWAY_PORT: 'API_GATEWAY_PORT',
    API_GATEWAY_HOST: 'API_GATEWAY_HOST',
    CORS_ORIGINS: 'CORS_ORIGINS',
    CORS_CREDENTIALS: 'CORS_CREDENTIALS',

    USER_SERVICE_ID: 'USER_SERVICE_ID',
    USER_SERVICE_NAME: 'USER_SERVICE_NAME',
    USER_SERVICE_PORT: 'USER_SERVICE_PORT',
    USER_SERVICE_HOST: 'USER_SERVICE_HOST', 
    
    SERVICE_TIMEOUT: 'SERVICE_TIMEOUT',

    JWT_SECRET: 'JWT_SECRET',
    JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',

    RABBITMQ_URL: 'RABBITMQ_URL',
    RABBITMQ_NOTIFICATIONS_QUEUE: 'RABBITMQ_NOTIFICATIONS_QUEUE',
    RABBITMQ_DEAD_LETTER_QUEUE: 'RABBITMQ_DEAD_LETTER_QUEUE',
    RABBITMQ_NOTIFICATION_EXCHANGE: 'RABBITMQ_NOTIFICATION_EXCHANGE',
    RABBITMQ_DEAD_LETTER_EXCHANGE: 'RABBITMQ_DEAD_LETTER_EXCHANGE',
    RABBITMQ_MESSAGE_TTL: 'RABBITMQ_MESSAGE_TTL',
    RABBITMQ_DLQ_MESSAGE_TTL: 'RABBITMQ_DLQ_MESSAGE_TTL',

    //EMAIL_PROVIDER: 'EMAIL_PROVIDER',
    //EMAIL_API_KEY: 'EMAIL_API_KEY',
    //EMAIL_FROM: 'EMAIL_FROM',
    EMAIL_TEMPLATE_DIR: 'EMAIL_TEMPLATE_DIR',

    EMAIL_HOST: 'EMAIL_HOST',
    EMAIL_PORT: 'EMAIL_PORT',
    EMAIL_SECURE: 'EMAIL_SECURE',
    EMAIL_USER: 'EMAIL_USER',
    EMAIL_PASSWORD: 'EMAIL_PASSWORD',

    NOTIFICATION_SERVICE_ID: 'NOTIFICATION_SERVICE_ID',
    NOTIFICATION_SERVICE_NAME: 'NOTIFICATION_SERVICE_NAME',
    NOTIFICATION_SERVICE_PORT: 'NOTIFICATION_SERVICE_PORT',
    NOTIFICATION_SERVICE_HOST: 'NOTIFICATION_SERVICE_HOST',
    //NOTIFICATION_SERVICE_TIMEOUT: 'NOTIFICATION_SERVICE_TIMEOUT',
    NOTIFICATION_RETRY_ATTEMPTS: 'NOTIFICATION_RETRY_ATTEMPTS',
    NOTIFICATION_RETRY_DELAY: 'NOTIFICATION_RETRY_DELAY',

    ASSESSMENT_SERVICE_ID: 'ASSESSMENT_SERVICE_ID',
    ASSESSMENT_SERVICE_NAME: 'ASSESSMENT_SERVICE_NAME',
    ASSESSMENT_SERVICE_PORT: 'ASSESSMENT_SERVICE_PORT',
    ASSESSMENT_SERVICE_HOST: 'ASSESSMENT_SERVICE_HOST',

    REPORT_SERVICE_ID: 'REPORT_SERVICE_ID',
    REPORT_SERVICE_NAME: 'REPORT_SERVICE_NAME',
    REPORT_SERVICE_PORT: 'REPORT_SERVICE_PORT',
    REPORT_SERVICE_HOST: 'REPORT_SERVICE_HOST',
}