export const ENV_KEYS = {
    NODE_ENV: 'NODE_ENV',

    DATABASE_URL: 'DATABASE_URL',
    DATABASE_SCHEMA: 'DATABASE_SCHEMA',
    TEST_DATABASE_SCHEMA: 'TEST_DATABASE_SCHEMA',
    DATABASE_POOL_MIN: 'DATABASE_POOL_MIN',
    DATABASE_POOL_MAX: 'DATABASE_POOL_MAX',
    
    CONSUL_HOST: 'CONSUL_HOST',
    CONSUL_PORT: 'CONSUL_PORT',
    
    API_GATEWAY_ID: 'API_GATEWAY_ID',
    API_GATEWAY_NAME: 'API_GATEWAY_NAME',
    API_GATEWAY_PORT: 'API_GATEWAY_PORT',
    API_GATEWAY_HOST: 'API_GATEWAY_HOST',

    USER_SERVICE_ID: 'USER_SERVICE_ID',
    USER_SERVICE_NAME: 'USER_SERVICE_NAME',
    USER_SERVICE_PORT: 'USER_SERVICE_PORT',
    USER_SERVICE_HOST: 'USER_SERVICE_HOST', 
    
    SERVICE_TIMEOUT: 'SERVICE_TIMEOUT',

    JWT_SECRET: 'JWT_SECRET',
    JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
}